Handle strncpy in a way compatible with gcc-9 linting
gcc-9 is now more rigorous about ensuring strncpy() is used correctly and
errors out if the bound argument appears to be derived from the source
argument:
/usr/include/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
Leverage this compiler functionality, and in the process fix a possible
1-byte buffer overflow.